# Generated by Django 5.1.1 on 2024-09-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('clicks', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
